# Generated by Django 5.0.6 on 2026-08-20 04:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digital', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opening_balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_currency', models.CharField(default='NPR', max_length=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('key', models.SlugField()),
                ('label', models.CharField(max_length=100)),
                ('color', models.CharField(default='#6b7280', max_length=20)),
                ('icon', models.CharField(default='🏷️', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'unique_together': {('user', 'type', 'key')},
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer'), ('remittance', 'Remittance')], max_length=12)),
                ('account', models.CharField(choices=[('digital', 'Digital'), ('cash', 'Cash')], max_length=10)),
                ('to_account', models.CharField(blank=True, choices=[('digital', 'Digital'), ('cash', 'Cash')], max_length=10, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='NPR', max_length=8)),
                ('date', models.DateField()),
                ('source', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('from_country', models.CharField(blank=True, default='', max_length=100)),
                ('to_country', models.CharField(blank=True, default='', max_length=100)),
                ('sent_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('sent_currency', models.CharField(blank=True, default='', max_length=8)),
                ('recipient', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'type'], name='tracker_rec_user_id_b6dbb8_idx'), models.Index(fields=['user', 'date'], name='tracker_rec_user_id_22bc3b_idx'), models.Index(fields=['user', 'account'], name='tracker_rec_user_id_c8a9e7_idx')],
            },
        ),
    ]
