# Generated by Django 5.0.6 on 2026-08-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openingbalance',
            name='currency',
            field=models.CharField(default='NPR', max_length=8),
        ),
    ]